# Generated by Django 5.1.2 on 2024-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldata',
            name='Datefild',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tbldata',
            name='timefild',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
